# -*- coding: utf-8 -*-
"""Fácil de 10. Clustering I .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1peD4ohLcrqm9Jt-YH-OrRrevnoB1LHy_
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""El dataset con el que vamos a trabajar contiene la medida de longitud del pico, de profundidad del pico, longitud de aletas y masa corporal de diferentes pinguinos. Vamos a estudiar mediante clustering cuantos grupos de pinguinos hay en los datos.

[Enlace al dataset](https://drive.google.com/file/d/1qnwJBBdjuE1bcUul3VZ5h7r_ryweXMNo/view?usp=sharing)

Importa el dataset en la variable penguins.
"""

penguins = pd.read_csv('/content/penguins_size.csv')

#@title Comprueba la creación del dataframe
def check():
  if str(penguins.tail())=='     culmen_length_mm  culmen_depth_mm  flipper_length_mm  body_mass_g\n339               NaN              NaN                NaN          NaN\n340              46.8             14.3              215.0       4850.0\n341              50.4             15.7              222.0       5750.0\n342              45.2             14.8              212.0       5200.0\n343              49.9             16.1              213.0       5400.0':
    return 'Creación correcta'
  else:
    return 'Incorrecto, comprueba el datafame'
check()

"""Comprueba cuantas filas tiene el dataset"""

penguins.shape[0]

"""Comprueba los 5 primeros elementos del dataframe."""

penguins.head()

"""Comprueba cuantos missing values tiene cada columna"""

penguins.isna().sum()

"""Dado el número de datos podemos permitirnos eliminar aquellas filas con missing values"""

penguins.dropna(inplace=True)

"""#Ejercicio 1 dendograma

Realiza el dendograma para agrupar a los pinguinos según la longitud del pico, profundidad del pico, longitud de aletas y masa corporal.
"""

import scipy.cluster.hierarchy as sch

dendograma = sch.dendrogram(sch.linkage(penguins[['culmen_length_mm','culmen_depth_mm','flipper_length_mm','body_mass_g']], method='ward'))
plt.title('Dendograma')
plt.xlabel('Pinguinos')
plt.ylabel('Distancia Euclidiana')
plt.show()

"""¿Según el dendograma cuantos tipos de pingüinos hay? almacena tu respuesta como número entero en la variable res1"""

res1=2

"""¿Si quisiéramos sacar otro grupo más, que rama dividiríamos la roja o la verde basandonos en la distancia? almacena el color de la rama que dividiríamos en la variable res2."""

res2='verde'

"""#Ejercicio 2 Clustering Aglomerativo

Vamos a crear el modelo de clusterring aglomerativo de sklearn
"""

# Importamos el algoritmo de sklearn
from sklearn.cluster import AgglomerativeClustering

"""Representa la longitud de pico frente a profundidad de pico y la longitud de aleta frente a masa corporal."""

hc = AgglomerativeClustering(n_clusters=2, metric='euclidean')
hc.fit_predict(penguins[['culmen_length_mm','culmen_depth_mm','flipper_length_mm','body_mass_g']])
fig, (ax1,ax2) = plt.subplots(2)
ax1.scatter(penguins['culmen_length_mm'],penguins['culmen_depth_mm'],c=hc.fit_predict(penguins[['culmen_length_mm','culmen_depth_mm','flipper_length_mm','body_mass_g']]))
ax2.scatter(penguins['flipper_length_mm'],penguins['body_mass_g'],c=hc.fit_predict(penguins[['culmen_length_mm','culmen_depth_mm','flipper_length_mm','body_mass_g']]))
plt.show()

"""¿Cuál de las dos gráficas describe mejor la diferencia entre grupos? Almacena 'medidas del pico' o 'aletas y masa corporal' en la variable res3."""

res3= 'aletas y masa corporal'

"""#Ejercicio 3 Algoritmo K-means

En esta ocasión en lugar de utilizar el dendograma realizaremos el clustering mediante K-means
"""

from sklearn.cluster import KMeans

wcss = []

for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, random_state=42)  # Initialize KMeans with the current cluster number
    kmeans.fit(penguins[['culmen_length_mm','culmen_depth_mm','flipper_length_mm','body_mass_g']])  # Fit the model
    wcss.append(kmeans.inertia_)  # Append the inertia_ (WCSS) to the list


plt.plot(range(1, 11), wcss)
plt.title('Método del codo')
plt.xlabel('Número de clusters')
plt.ylabel('WCSS')
plt.show()

"""¿Cuál sería el número óptimo de clusters según el método del codo? Almacena tu respuesta como número entero en la variable res4"""

res4=4

"""Realiza la predicción mediante k-means con 4 clusters"""

kmeans = KMeans(n_clusters=4, random_state=42)
kmeans.fit(penguins[['culmen_length_mm','culmen_depth_mm','flipper_length_mm','body_mass_g']])

"""¿Sigue siendo válida la gráfica que elegiste en la respuesta 3 para describir los clusters? Responde mediante un booleano en la variable res5"""

fig, (ax1,ax2) = plt.subplots(2)
ax1.scatter(penguins['culmen_length_mm'],penguins['culmen_depth_mm'],c=kmeans.fit_predict(penguins[['culmen_length_mm','culmen_depth_mm','flipper_length_mm','body_mass_g']]))
ax2.scatter(penguins['flipper_length_mm'],penguins['body_mass_g'],c=kmeans.fit_predict(penguins[['culmen_length_mm','culmen_depth_mm','flipper_length_mm','body_mass_g']]))
plt.show()

res5=True

#@title Consigue el Token para corregir el ejercicio en Nodd3r
import hashlib

correct = str(res1)+str(res2) +str(res3) +str(res4) +str(res5)
pwd = hashlib.sha256(str(correct).encode())
print('El token para corregir en Nodd3r es:\n',pwd.hexdigest())